(define (pow x) (* x x))
(define (abs x)
  (if (< x 0) (- x) x)
)
(define (>= x y)
  (or (> x y) (= x y))
)

(define (sqrt_try guess x)
  (if (good_enough? guess x)
    guess
    (sqrt_try (improve guess x) x)
  )
)
(define (good_enough? guess x)
  (< (abs (- (pow guess) x)) 0.001)
)
(define (improve guess x)
  (average guess (/ x guess))
)
(define (average x y)
  (/ (+ x y) 2)
)
(define (sqrt x)
  (sqrt_try 1.0 x)
)