(define (pow x) (* x x))
(define (abs x)
  (if (< x 0) (- x) x))
(define (>= x y)
  (or (> x y) (= x y)))
(define (average x y)
  (/ (+ x y) 2))

(define (sqrt x)
  (define (good_enough? old_guess new_guess)
    (> 0.01 (/ (abs (- new_guess old_guess)) old_guess)))
  (define (improve guess x)
    (average guess (/ x guess)))
  (define (sqrt_try guess x)
    (if (good_enough? guess (improve guess x))
      (improve guess x)
      (sqrt_try (improve guess x) x)))
  (sqrt_try 1.0 x))
